/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastTuple/FastTupleXXX.ramet" and regenerate instead.
 */

package com.flora.root.fast.container.tuple;

import com.flora.root.tag.ReadOnly;
import java.io.Serial;
import java.io.Serializable;

/**
 * 原始类型特化的快速元组。
 * <p>避免装箱开销，提供对原始类型元素的高效存储和访问。</p>
 */
@ReadOnly
public final class FastTupleLLB implements Serializable, Cloneable, Comparable<FastTupleLLB> {
    @Serial
    private static final long serialVersionUID = 1L;

    /** 第1个元素 */
    private final long v1;
    /** 第2个元素 */
    private final long v2;
    /** 第3个元素 */
    private final byte v3;

    /**
     * 创建一个包含指定原始类型元素的快速元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     */
    public FastTupleLLB(long v1,long v2,byte v3){
        this.v1 = v1;
        this.v2 = v2;
        this.v3 = v3;
    }

    /**
     * 返回第1个元素。
     *
     * @return 第1个元素
     */
    public long getL1() { return v1; }
    /**
     * 返回第2个元素。
     *
     * @return 第2个元素
     */
    public long getL2() { return v2; }
    /**
     * 返回第3个元素。
     *
     * @return 第3个元素
     */
    public byte getB1() { return v3; }

    /**
     * 返回此快速元组的浅拷贝。
     * <p>元组不可变，直接返回自身（等价实例可安全共享）。</p>
     *
     * @return 此元组实例
     */
    @Override
    public FastTupleLLB clone() {
        return this;
    }

    /**
     * 按字典顺序比较此快速元组与指定元组。
     * <p>逐元素比较，首个不同元素决定结果；全部相同则返回 0。</p>
     *
     * @param that 要比较的元组
     * @return 如果此元组小于、等于或大于指定元组，则返回负整数、零或正整数
     */
    @Override
    public int compareTo(FastTupleLLB that) {
        int c1 = Long.compare(this.v1, that.v1);
        if (c1 != 0) return c1;
        int c2 = Long.compare(this.v2, that.v2);
        if (c2 != 0) return c2;
        int c3 = Byte.compare(this.v3, that.v3);
        if (c3 != 0) return c3;
        return 0;
    }

    /**
     * 比较此快速元组与指定对象是否相等。
     *
     * @param o 要比较的对象
     * @return 如果所有元素值相等则返回 true
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FastTupleLLB that)) return false;
        return this.v1 == that.v1
            && this.v2 == that.v2
            && this.v3 == that.v3
;
    }

    /**
     * 返回此快速元组的哈希码。
     *
     * @return 哈希码值
     */
    @Override
    public int hashCode() {
        int result = Long.hashCode(v1);
        result = 31 * result + Long.hashCode(v2);
        result = 31 * result + Byte.hashCode(v3);
        return result;
    }

    /**
     * 返回此快速元组的字符串表示。
     * <p>格式为 {@code <v1, v2, ...>}。</p>
     *
     * @return 字符串表示
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("<");
        sb.append(v1).append(", ");
        sb.append(v2).append(", ");
        sb.append(v3);
        return sb.append(">").toString();
    }
}
