package com.flora.codegen;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 端到端验证「代码生成门面」CodeGenUtil 的边界与行为：
 * 纯数据输入/输出，覆盖简单生成、include、错误路径等。
 */
class CodeGenUtilTest {

    @Test
    void simpleTemplateGeneratesOneFile() throws IOException {
        String tpl = """
                <#meta>
                @Param{ pkg: "com.x", name: "Foo" }
                @Path{ "Foo.java" }
                </#meta>
                package ${pkg};
                public class ${name} {}
                """;

        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(tpl, Map.of());

        assertEquals(1, results.size());
        CodeGenUtil.Generated g = results.get(0);
        assertEquals("Foo.java", g.relativePath());
        assertTrue(g.content().contains("package com.x;"));
        assertTrue(g.content().contains("public class Foo {}"));
    }

    @Test
    void missingPathDeclarationReturnsEmpty() throws IOException {
        String tpl = """
                <#meta>
                @Param{ pkg: "com.x" }
                </#meta>
                package ${pkg};
                """;

        assertTrue(CodeGenUtil.generate(tpl, Map.of()).isEmpty());
    }

    @Test
    void includeRendersNestedTemplate() throws IOException {
        String included = """
                [${greeting}]
                """;
        String host = """
                <#meta>
                @Param{ greeting: "hi" }
                @Path{ "Host.java" }
                </#meta>
                before <#include "inc.ftl"> after
                """;

        CompiledTemplate compiled = CodeGenUtil.precompile(included);
        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(host, Map.of("inc.ftl", compiled));

        assertEquals(1, results.size());
        assertEquals("Host.java", results.get(0).relativePath());
        String flat = results.get(0).content().replace("\n", "");
        assertTrue(flat.contains("before [hi] after"), flat);
    }

    @Test
    void ifForAndMacroRender() throws IOException {
        String tpl = """
                <#meta>
                @Param{ useTag: true, items: ["a", "b"] }
                @Path{ "M.java" }
                </#meta>
                <#macro shout:w>${capitalize(w)}!</#macro>
                <#if useTag>tagged</#if>
                <#for it:items>-${it}-</#for>
                <@shout "go"/>
                """;

        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(tpl, Map.of());
        String content = results.get(0).content();
        assertTrue(content.contains("tagged"), content);
        assertTrue(content.contains("-a-"), content);
        assertTrue(content.contains("-b-"), content);
        assertTrue(content.contains("Go!"), content);
    }

    @Test
    void staticPathWithoutInterpolation() throws IOException {
        String tpl = "<#meta>@Path{ \"Static.java\" }</#meta>body";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertEquals("Static.java", g.relativePath());
        assertTrue(g.content().contains("body"));
    }

    @Test
    void pathOnlyTemplateWithoutManifestKeepsPath() throws IOException {
        String tpl = "<#meta>@Path{ \"Only.java\" }</#meta>hello";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertEquals("Only.java", g.relativePath());
        assertTrue(g.content().contains("hello"));
    }

    @Test
    void autoWarningAddedForJavaFiles() throws IOException {
        String tpl = "<#meta>@Path{ \"Test.java\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("/*\n"), "应注入 /* 风格注释");
        assertTrue(g.content().contains("auto generated by"), "应包含警告文本");
        assertTrue(g.content().contains("content"), "应保留原内容");
    }

    @Test
    void autoWarningDisabledViaConfig() throws IOException {
        String tpl = "<#meta>@Config{ autoWarning: false } @Path{ \"Test.java\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertFalse(g.content().contains("auto generated by"), "关闭后不应注入");
        assertEquals("content", g.content());
    }

    @Test
    void autoWarningSkippedForUnknownExtension() throws IOException {
        String tpl = "<#meta>@Path{ \"data.bin\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertFalse(g.content().contains("auto generated by"), "未知扩展名不应注入");
        assertEquals("content", g.content());
    }

    @Test
    void autoWarningUsesHashStyleForPython() throws IOException {
        String tpl = "<#meta>@Path{ \"script.py\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("# "), "Python 应为 # 风格注释");
        assertTrue(g.content().contains("content"));
    }

    @Test
    void autoWarningUsesHtmlStyleForXml() throws IOException {
        String tpl = "<#meta>@Path{ \"config.xml\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("<!--\n"), "XML 应为 <!-- 风格注释");
        assertTrue(g.content().contains("content"));
    }

    @Test
    void autoWarningUsesDashStyleForSql() throws IOException {
        String tpl = "<#meta>@Path{ \"schema.sql\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("-- "), "SQL 应为 -- 风格注释");
        assertTrue(g.content().contains("content"));
    }

    @Test
    void autoWarningUsesPercentStyleForTex() throws IOException {
        String tpl = "<#meta>@Path{ \"paper.tex\" }</#meta>content";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("% "), "TeX 应为 % 风格注释");
        assertTrue(g.content().contains("content"));
    }

    // ---- shebang 保护 ----

    @Test
    void warningInsertedAfterShebangForShFiles() throws IOException {
        String tpl = "<#meta>@Path{ \"script.sh\"}</#meta>#!/bin/bash\necho hello";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("#!/bin/bash\n"), "shebang 必须在首行");
        assertTrue(g.content().contains("# WARNING: Do NOT edit manually"),
                "警告注释应存在");
        assertTrue(g.content().contains("auto generated by flora-ramet"),
                "应包含 auto generated 标记");
        assertTrue(g.content().contains("echo hello"), "原内容应保留");
        // 验证顺序: shebang → 警告 → 原内容
        String body = g.content();
        int shebangEnd = body.indexOf('\n');
        String afterShebang = body.substring(shebangEnd + 1);
        assertTrue(afterShebang.startsWith("# "), "警告注释应在 shebang 之后紧接出现");
    }

    @Test
    void warningInsertedAfterShebangForPythonFiles() throws IOException {
        String tpl = "<#meta>@Path{ \"script.py\" }</#meta>#!/usr/bin/env python3\nprint('hello')";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("#!/usr/bin/env python3\n"), "shebang 必须在首行");
        assertTrue(g.content().contains("print('hello')"), "原内容应保留");
    }

    @Test
    void shebangPreservedWithBlockCommentStyle() throws IOException {
        // 虽然 ffi 场景罕见，但 BLOCK 风格的 prepend 也应尊重 shebang
        String tpl = "<#meta>@Path{ \"Generator.java\" }</#meta>#!/usr/bin/env jshell\nSystem.out.println(1);";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("#!/usr/bin/env jshell\n"), "shebang 必须在首行");
        assertTrue(g.content().contains("/*\n"), "/* 注释应在 shebang 之后");
    }

    @Test
    void shebangPreservedWithHtmlCommentStyle() throws IOException {
        String tpl = "<#meta>@Path{ \"script.xml\" }</#meta>#!/usr/bin/env xslt\n<root/>";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertTrue(g.content().startsWith("#!/usr/bin/env xslt\n"), "shebang 必须在首行");
        assertTrue(g.content().contains("<!--\n"), "<!-- 注释应在 shebang 之后");
    }

    @Test
    void warningAfterShebangDisabledViaConfig() throws IOException {
        String tpl = "<#meta>@Config{ autoWarning: false } @Path{ \"script.sh\" }</#meta>#!/bin/bash\necho hello";
        CodeGenUtil.Generated g = CodeGenUtil.generate(tpl, Map.of()).get(0);
        assertEquals("#!/bin/bash\necho hello", g.content(), "关闭后内容应完全不变");
    }

    // ---- 单文件合并模式 ----

    @Test
    void samePathCombineMergesIntoSingleFile() throws IOException {
        // 模拟 FastTupleFactory 场景：@Cartesian 产生多值但 @Path 固定
        String tpl = """
                <#meta>
                @Param{ base: "X" }
                @Cartesian{ T: ["A", "B", "C"] }
                @Path{ "Factory.java" }
                </#meta>
                public class Factory {
                <#for t:T>
                    public void make${t}() {}
                </#for>
                }
                """;

        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(tpl, Map.of());

        assertEquals(1, results.size(), "同路径应合并为单一文件");
        CodeGenUtil.Generated g = results.get(0);
        assertEquals("Factory.java", g.relativePath());

        String content = g.content();
        assertTrue(content.contains("makeA()"), "应包含 A 的方法");
        assertTrue(content.contains("makeB()"), "应包含 B 的方法");
        assertTrue(content.contains("makeC()"), "应包含 C 的方法");

        long classCount = content.lines().filter(l -> l.contains("class Factory")).count();
        assertEquals(1, classCount, "不应有重复的 class 声明");
    }

    @Test
    void differentPathsStillGenerateMultipleFiles() throws IOException {
        String tpl = "<#meta>@Cartesian{K:[\"X\",\"Y\"]}@Path{\"${K}.java\"}</#meta>class ${K} {}";
        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(tpl, Map.of());
        assertEquals(2, results.size(), "不同路径应生成多个文件");
    }

    @Test
    void actualFactoryTemplateProducesSingleFile() throws IOException {
        // 使用实际的 FastTupleFactory.ramet 模板内容
        java.nio.file.Path tplPath = java.nio.file.Path.of(
                "../flora-root/src/main/templates/fastTuple/FastTupleFactory.ramet");
        if (!Files.exists(tplPath)) {
            System.out.println("SKIP: Factory template not found at " + tplPath);
            return;
        }
        String tpl = Files.readString(tplPath);
        List<CodeGenUtil.Generated> results = CodeGenUtil.generate(tpl, Map.of());

        // 必须只输出一个文件
        assertEquals(1, results.size(), "Factory 模板应合并为单一输出文件");
        CodeGenUtil.Generated g = results.get(0);
        assertEquals("com/flora/fast/container/tuple/FastTupleFactory.java", g.relativePath());

        // 内容应只有一个 class 声明
        long classCount = g.content().lines()
                .filter(l -> l.contains("class FastTupleFactory")).count();
        assertEquals(1, classCount, "应有且仅有 1 个 class 声明，实际: " + classCount);

        // 应包含多个 of 方法 (118 个组合)
        long methodCount = g.content().lines().filter(l -> l.contains("public static FastTuple")).count();
        assertTrue(methodCount >= 100, "应有 ~118 个 of 方法，实际: " + methodCount);
    }
}
