/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/ByteKeyFastHashMap.ramet" and regenerate instead.
 */

package com.flora.fast.container.map;

import com.flora.tag.ThreadFragile;
import com.flora.entropy.HashUtil;
import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.flora.fast.container.consumer.*;

/**
 * byte→Char 类型专用开地址哈希映射。
 * <p>Byte 键类型不支持零值作为空槽标记，使用独立标志位 trackOccupied[] 记录槽位占用状态。</p>
 */
@ThreadFragile
public class Byte2CharFastHashMap
    extends AbstractMap<Byte, Character> {

    private static final int MAX = 256;

    private byte[] keys;
    private char[] values;
    private boolean[] used;
    private int size;
    private int mask;
    private boolean containsZeroKey;
    private final float loadFactor;
    private int maxOccupied;
    private final int minCapacity;
    private char defaultReturnValue = '\u0000';

    // 当 values.length == MAX 时进入直接索引模式（keys == null），
    // 不再使用哈希/线性探测，直接以 key & 0xFF 为索引。

    /**
     * 构造一个默认容量（16）、默认负载因子（0.75）的空映射。
     */
    public Byte2CharFastHashMap() {
        this(16, 0.75f);
    }

    /**
     * 构造一个指定初始容量、默认负载因子（0.75）的空映射。
     *
     * @param initialCapacity 初始容量
     */
    public Byte2CharFastHashMap(int initialCapacity) {
        this(initialCapacity, 0.75f);
    }

    /**
     * 构造一个指定初始容量和负载因子的空映射。
     *
     * @param initialCapacity 初始容量，必须为正数
     * @param loadFactor      负载因子，必须在 (0, 1) 范围内
     * @throws IllegalArgumentException 如果 initialCapacity ≤ 0 或 loadFactor 不在 (0, 1) 范围内
     */
    public Byte2CharFastHashMap(int initialCapacity, float loadFactor) {
        if (initialCapacity <= 0) throw new IllegalArgumentException("Capacity must be positive");
        if (loadFactor <= 0 || loadFactor >= 1) throw new IllegalArgumentException("Load factor must be in (0, 1)");
        int capacity = tableSize(initialCapacity);
        this.keys = new byte[capacity + 1];
        this.values = new char[capacity + 1];
        this.mask = capacity - 1;
        this.loadFactor = loadFactor;
        this.maxOccupied = (int) (capacity * loadFactor);
        this.minCapacity = capacity;
    }

    // --- Map.containsKey(Object) ---

    /**
     * {@inheritDoc}
     *
     * @param key 键（Byte 类型）
     * @return 如果存在该键则返回 true，否则返回 false
     */
    @Override
    public boolean containsKey(Object key) {
        if (!(key instanceof Byte)) return false;
        return containsKey((byte) key);
    }

    /**
     * 判断映射中是否包含指定 byte 键。
     *
     * @param key 键
     * @return 如果存在该键则返回 true，否则返回 false
     */
    public boolean containsKey(byte key) {
        // --- 直接数组模式 ---
        if (keys == null) {
            return used[key & 0xFF];
        }
        // --- 哈希表模式 ---
        if (key == (byte)0) return containsZeroKey;
        int pos = (int) HashUtil.goldenHash(key) & mask;
        while (keys[pos] != (byte)0) {
            if (keys[pos] == key) return true;
            pos = (pos + 1) & mask;
        }
        return false;
    }

    // --- Map.get(Object) ---

    /**
     * {@inheritDoc}
     *
     * @param key 键（Byte 类型）
     * @return 键对应的值，若不存在则返回 null
     */
    @Override
    public Character get(Object key) {
        if (!(key instanceof Byte)) return null;
        byte kk = (byte) key;
        if (!containsKey(kk)) return null;
        return get(kk);
    }

    /**
     * 获取指定 byte 键对应的值。
     *
     * @param key 键
     * @return 键对应的值，若不存在则返回默认返回值
     */
    public char get(byte key) {
        return getOrDefault(key, defaultReturnValue);
    }

    /**
     * 获取指定 byte 键对应的值，若不存在则返回给定默认值。
     *
     * @param key          键
     * @param defaultValue 默认值
     * @return 键对应的值，若不存在则返回 {@code defaultValue}
     */
    public char getOrDefault(byte key, char defaultValue) {
        // --- 直接数组模式 ---
        if (keys == null) {
            int idx = key & 0xFF;
            return used[idx] ? values[idx] : defaultValue;
        }
        // --- 哈希表模式 ---
        if (key == (byte)0) return containsZeroKey ? values[values.length - 1] : defaultValue;
        int pos = (int) HashUtil.goldenHash(key) & mask;
        while (keys[pos] != (byte)0) {
            if (keys[pos] == key) return values[pos];
            pos = (pos + 1) & mask;
        }
        return defaultValue;
    }

    // --- Map.put(Byte, V_boxed) ---

    /**
     * {@inheritDoc}
     *
     * @param key   键（Byte 类型）
     * @param value 值
     * @return 键对应的旧值，若键之前不存在则返回 null
     */
    @Override
    public Character put(Byte key, Character value) {
        byte kk = (byte) key;
        char vv = (char) value;
        if (!containsKey(kk)) {
            put(kk, vv);
            return null;
        }
        return put(kk, vv);
    }

    /**
     * 将指定 byte 键与值关联。
     *
     * @param key   键
     * @param value 值
     * @return 键对应的旧值，若键之前不存在则返回默认返回值
     */
    public char put(byte key, char value) {
        // --- 直接数组模式 ---
        if (keys == null) {
            int idx = key & 0xFF;
            if (used[idx]) {
                char old = values[idx];
                values[idx] = value;
                return old;
            }
            values[idx] = value;
            used[idx] = true;
            size++;
            return defaultReturnValue;
        }
        // --- 哈希表模式 ---
        if (key == (byte)0) {
            if (containsZeroKey) {
                char old = values[values.length - 1];
                values[values.length - 1] = value;
                return old;
            }
            containsZeroKey = true;
            values[values.length - 1] = value;
            size++;
            if (size > maxOccupied) rehash(tableSize(values.length));
            return defaultReturnValue;
        }

        int pos = (int) HashUtil.goldenHash(key) & mask;
        while (keys[pos] != (byte)0) {
            if (keys[pos] == key) {
                char old = values[pos];
                values[pos] = value;
                return old;
            }
            pos = (pos + 1) & mask;
        }
        keys[pos] = key;
        values[pos] = value;
        size++;
        if (size > maxOccupied) rehash(tableSize(values.length));
        return defaultReturnValue;
    }

    // --- Map.remove(Object) ---

    /**
     * {@inheritDoc}
     *
     * @param key 键（Byte 类型）
     * @return 被移除的键对应的旧值，若键不存在则返回 null
     */
    @Override
    public Character remove(Object key) {
        if (!(key instanceof Byte)) return null;
        byte kk = (byte) key;
        if (!containsKey(kk)) return null;
        return remove(kk);
    }

    /**
     * 移除指定 byte 键及其关联的值。
     *
     * @param key 键
     * @return 被移除的键对应的旧值，若键不存在则返回默认返回值
     */
    public char remove(byte key) {
        // --- 直接数组模式 ---
        if (keys == null) {
            int idx = key & 0xFF;
            if (used[idx]) {
                char old = values[idx];
                used[idx] = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }
        // --- 哈希表模式 ---
        if (key == (byte)0) {
            if (containsZeroKey) {
                char old = values[values.length - 1];
                containsZeroKey = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }

        int pos = (int) HashUtil.goldenHash(key) & mask;
        while (keys[pos] != (byte)0) {
            if (keys[pos] == key) {
                char old = values[pos];
                keys[pos] = (byte)0;
                size--;
                shiftKeys(pos);
                tryShrink();
                return old;
            }
            pos = (pos + 1) & mask;
        }
        return defaultReturnValue;
    }

    // --- clear / size / isEmpty ---

    /**
     * 清空映射，移除所有键值对。
     */
    public void clear() {
        // --- 直接数组模式 ---
        if (keys == null) {
            Arrays.fill(used, false);
        } else {
            Arrays.fill(keys, (byte)0);
            containsZeroKey = false;
        }
        size = 0;
    }

    /**
     * 返回映射中的键值对数量。
     *
     * @return 键值对数量
     */
    public int size() {
        return size;
    }

    /**
     * 判断映射是否为空。
     *
     * @return 如果映射中不包含任何键值对则返回 true
     */
    public boolean isEmpty() {
        return size == 0;
    }

    // --- forEach ---

    /**
     * 对映射中的每个键值对执行指定操作。
     *
     * @param action 要执行的操作
     */
    public void forEach(Byte2CharConsumer action) {
        if (keys == null) {
            for (int i = 0; i < MAX; i++) {
                if (used[i]) action.accept((byte) i, values[i]);
            }
        } else {
            for (int i = 0; i <= mask; i++) {
                if (keys[i] == (byte)0) continue;
                action.accept(keys[i], values[i]);
            }
            if (containsZeroKey) action.accept((byte)0, values[values.length - 1]);
        }
    }

    /**
     * 设置默认返回值。
     *
     * @param v 默认返回值
     */
    public void defaultReturnValue(char v) {
        defaultReturnValue = v;
    }

    /**
     * 获取默认返回值。
     *
     * @return 默认返回值
     */
    public char defaultReturnValue() {
        return defaultReturnValue;
    }


    // --- entrySet() view ---

    /**
     * {@inheritDoc}
     *
     * @return 映射中所有键值对的 Set 视图
     */
    @Override
    public Set<Map.Entry<Byte, Character>> entrySet() {
        return new ByteEntrySet();
    }

    private static final class ByteFastEntry
            implements Map.Entry<Byte, Character> {
        byte k;
        char v;

        @Override public Byte getKey()     { return k; }
        @Override public Character getValue() { return v; }
        @Override public Character setValue(Character value) {
            Character old = v;
            v = (char) value;
            return old;
        }

        @Override public String toString() {
            return (k & 0xFF) + "=" + v;
        }
    }

    private final class ByteFastIterator
            implements Iterator<Map.Entry<Byte, Character>> {
        int cursor = 0;
        boolean zeroKeyPending;
        ByteFastEntry entry = new ByteFastEntry();

        ByteFastIterator() {
            if (keys == null) {
                advanceDirect();
            } else {
                zeroKeyPending = containsZeroKey;
                advanceHash();
            }
        }

        private void advanceDirect() {
            while (cursor < MAX && !used[cursor]) cursor++;
        }

        private void advanceHash() {
            while (cursor <= mask && keys[cursor] == (byte)0) cursor++;
        }

        @Override
        public boolean hasNext() {
            if (keys == null) return cursor < MAX;
            return zeroKeyPending || cursor <= mask;
        }

        @Override
        public Map.Entry<Byte, Character> next() {
            if (!hasNext()) throw new NoSuchElementException();
            if (zeroKeyPending) {
                zeroKeyPending = false;
                entry.k = (byte) 0;
                entry.v = values[values.length - 1];
            } else if (keys == null) {
                entry.k = (byte) cursor;
                entry.v = values[cursor];
                cursor++;
                advanceDirect();
            } else {
                entry.k = keys[cursor];
                entry.v = values[cursor];
                cursor++;
                advanceHash();
            }
            return entry;
        }
    }

    private final class ByteEntrySet
            extends AbstractSet<Map.Entry<Byte, Character>> {
        @Override
        public Iterator<Map.Entry<Byte, Character>> iterator() {
            return new ByteFastIterator();
        }

        @Override
        public int size() {
            return size;
        }

        @Override @SuppressWarnings("unchecked")
        public boolean contains(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Byte, Character> e = (Map.Entry<Byte, Character>) o;
            Object k = e.getKey();
            if (!(k instanceof Byte)) return false;
            byte kk = (byte) k;
            if (!containsKey(kk)) return false;
            char v = get(kk);
            return Objects.equals(v, e.getValue());
        }

        @Override @SuppressWarnings("unchecked")
        public boolean remove(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Byte, Character> e = (Map.Entry<Byte, Character>) o;
            Object k = e.getKey();
            if (!(k instanceof Byte)) return false;
            byte kk = (byte) k;
            if (!containsKey(kk)) return false;
            char v = get(kk);
            if (!Objects.equals(v, e.getValue())) return false;
            Byte2CharFastHashMap.this.remove(kk);
            return true;
        }
    }


    // --- private helpers (unchanged) ---

    private void tryShrink() {
        // --- 直接数组模式：考虑回退到哈希表 ---
        if (keys == null) {
            if (MAX <= minCapacity) return;
            if (size > MAX / 4) return;
            int newCapacity = Math.max(minCapacity, MAX / 2);
            rehash(newCapacity);
            return;
        }
        int capacity = keys.length - 1;
        if (capacity <= minCapacity) return;
        if (capacity <= 16) return;
        if (size > maxOccupied / 4) return;

        int newCapacity = Math.max(minCapacity, capacity / 2);
        rehash(newCapacity);
    }

    private void shiftKeys(int pos) {
        int hole = pos;
        int scan = pos;
        byte[] key = this.keys;
        char[] value = this.values;

        while (true) {
            scan = (scan + 1) & mask;

            if (key[scan] == (byte)0) {
                key[hole] = (byte)0;
                return;
            }

            byte curr = key[scan];
            int slot = (int) HashUtil.goldenHash(curr) & mask;

            if (hole <= scan ? hole >= slot || slot > scan : hole >= slot && slot > scan) {
                key[hole] = curr;
                value[hole] = value[scan];
                hole = scan;
            }
        }
    }

    private void rehash(int newCapacity) {
        // --- 直接数组 → 哈希表（回退） ---
        if (keys == null) {
            boolean[] oldUsed = used;
            char[] oldValues = values;

            int newMask = newCapacity - 1;
            keys = new byte[newCapacity + 1];
            values = new char[newCapacity + 1];
            mask = newMask;
            maxOccupied = (int) (newCapacity * loadFactor);
            containsZeroKey = false;

            for (int i = 0; i < MAX; i++) {
                if (oldUsed[i]) {
                    if (i == 0) {
                        containsZeroKey = true;
                        values[keys.length - 1] = oldValues[0];
                    } else {
                        byte k = (byte) i;
                        int pos = (int) HashUtil.goldenHash(k) & mask;
                        while (keys[pos] != (byte)0) pos = (pos + 1) & mask;
                        keys[pos] = k;
                        values[pos] = oldValues[i];
                    }
                }
            }
            return;
        }
        // --- 切换到直接数组模式 ---
        if (newCapacity >= MAX) {
            // 不再需要 keys/containsZeroKey/mask/maxOccupied
            byte[] oldKeys = keys;
            char[] oldValues = values;
            boolean hadZero = containsZeroKey;
            char oldZeroVal = hadZero ? oldValues[oldValues.length - 1] : '\u0000';

            values = new char[MAX];
            used = new boolean[MAX];
            keys = null;
            mask = 0;
            maxOccupied = Integer.MAX_VALUE;

            for (int i = 0; i < oldKeys.length - 1; i++) {
                if (oldKeys[i] != (byte)0) {
                    int idx = oldKeys[i] & 0xFF;
                    values[idx] = oldValues[i];
                    used[idx] = true;
                }
            }
            if (hadZero) {
                values[0] = oldZeroVal;
                used[0] = true;
            }
            return;
        }
        // --- 旧 rehash 逻辑（容量 < 256 时的哈希表内部扩容） ---
        byte[] oldKeys = keys;
        char[] oldValues = values;
        boolean oldHasZero = containsZeroKey;
        char oldZeroVal = oldHasZero ? oldValues[oldValues.length - 1] : '\u0000';

        int newMask = newCapacity - 1;
        keys = new byte[newCapacity + 1];
        values = new char[newCapacity + 1];
        mask = newMask;
        maxOccupied = (int) (newCapacity * loadFactor);

        if (containsZeroKey) {
            values[keys.length - 1] = oldZeroVal;
        }

        for (int i = 0; i < oldKeys.length - 1; i++) {
            if (oldKeys[i] != (byte)0) {
                int pos = (int) HashUtil.goldenHash(oldKeys[i]) & mask;
                while (keys[pos] != (byte)0) pos = (pos + 1) & mask;
                keys[pos] = oldKeys[i];
                values[pos] = oldValues[i];
            }
        }
    }

    private static int tableSize(int n) {
        int p = 1;
        while (p < n) p <<= 1;
        return Math.max(p, 16);
    }
}
