/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/FastHashMap.ramet" and regenerate instead.
 */

package com.flora.fast.container.map;

import com.flora.tag.ThreadFragile;
import com.flora.entropy.HashUtil;
import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.flora.fast.container.consumer.*;
/**
 * Char→Int 类型专用开地址哈希映射。
 * <p>使用开放寻址法 + 线性探测，零值作为空槽标记。
 * 避免装箱拆箱开销，适合高性能场景。</p>
 *
 * @param <K> 键类型
 * @param <V> 值类型
 */
@ThreadFragile
public class Char2IntFastHashMap
    extends AbstractMap<Character, Integer> {

    private char[] keys;
    private int[] values;
    private int size;
    private int mask;
    private boolean containsZeroKey;
    private final float loadFactor;
    private int maxOccupied;
    private final int minCapacity;
    private int defaultReturnValue = -1;


    /** 创建默认容量(16)、默认负载因子(0.75)的映射。 */
    public Char2IntFastHashMap() {
        this(16, 0.75f);
    }

    public Char2IntFastHashMap(int initialCapacity) {
        this(initialCapacity, 0.75f);
    }

    public Char2IntFastHashMap(int initialCapacity, float loadFactor) {
        if (initialCapacity <= 0) throw new IllegalArgumentException("Capacity must be positive");
        if (loadFactor <= 0 || loadFactor >= 1) throw new IllegalArgumentException("Load factor must be in (0, 1)");
        int capacity = tableSize(initialCapacity);
        this.keys = new char[capacity + 1];
        this.values = new int[capacity + 1];
        this.mask = capacity - 1;
        this.loadFactor = loadFactor;
        this.maxOccupied = (int) (capacity * loadFactor);
        this.minCapacity = capacity;
    }

    // --- primitive K: add Map.get(Object) etc. delegating via cast ---

    /** 是否包含指定键。 */
    public boolean containsKey(char key) {
        if (key == '\0') return containsZeroKey;
        int pos = hash(key) & mask;
        while (keys[pos] != '\0') {
            if (keys[pos] == key) return true;
            pos = (pos + 1) & mask;
        }
        return false;
    }

    @Override
    public boolean containsKey(Object key) {
        if (!(key instanceof Character)) return false;
        return containsKey((char) (Character) key);
    }

    /** 获取键对应的值。@return 值或默认返回值 */
    public int get(char key) {
        return getOrDefault(key, defaultReturnValue);
    }

    @Override
    public Integer get(Object key) {
        if (!(key instanceof Character)) return null;
        char kk = (char) (Character) key;
        if (!containsKey(kk)) return null;
        return get(kk);
    }

    public int getOrDefault(char key, int defaultValue) {
        if (key == '\0') return containsZeroKey ? values[values.length - 1] : defaultValue;
        int pos = hash(key) & mask;
        while (keys[pos] != '\0') {
            if (keys[pos] == key) return values[pos];
            pos = (pos + 1) & mask;
        }
        return defaultValue;
    }

    /** 放入键值对。@return 旧值或默认返回值 */
    public int put(char key, int value) {
        if (key == '\0') {
            if (containsZeroKey) {
                int old = values[values.length - 1];
                values[values.length - 1] = value;
                return old;
            }
            containsZeroKey = true;
            values[values.length - 1] = value;
            size++;
            if (size > maxOccupied) rehash(tableSize(values.length));
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != '\0') {
            if (keys[pos] == key) {
                int old = values[pos];
                values[pos] = value;
                return old;
            }
            pos = (pos + 1) & mask;
        }
        keys[pos] = key;
        values[pos] = value;
        size++;
        if (size > maxOccupied) rehash(tableSize(values.length));
        return defaultReturnValue;
    }

    @Override
    public Integer put(Character key, Integer value) {
        char kk = (char) key;
        int vv = (int) value;
        if (!containsKey(kk)) {
            put(kk, vv);
            return null;
        }
        return put(kk, vv);
    }

    /** 移除键值对。@return 旧值或默认返回值 */
    public int remove(char key) {
        if (key == '\0') {
            if (containsZeroKey) {
                int old = values[values.length - 1];
                containsZeroKey = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != '\0') {
            if (keys[pos] == key) {
                int old = values[pos];
                keys[pos] = '\0';
                size--;
                shiftKeys(pos);
                tryShrink();
                return old;
            }
            pos = (pos + 1) & mask;
        }
        return defaultReturnValue;
    }

    @Override
    public Integer remove(Object key) {
        if (!(key instanceof Character)) return null;
        char kk = (char) (Character) key;
        if (!containsKey(kk)) return null;
        return remove(kk);
    }
    /** 清空映射。 */
    public void clear() {
        Arrays.fill(keys, '\0');
        containsZeroKey = false;
        size = 0;
    }

    /** 返回条目数。 */
    public int size() {
        return size;
    }

    /** 映射是否为空。 */
    public boolean isEmpty() {
        return size == 0;
    }

    /** 遍历所有键值对。@param action 消费接口 */
    public void forEach(Char2IntConsumer action) {
        for (int pos = 0; pos <= mask; pos++) {
            if (!(keys[pos] != '\0')) continue;
            action.accept(keys[pos], values[pos]);
        }
        if (containsZeroKey) action.accept('\0', values[values.length - 1]);
    }

    public void defaultReturnValue(int v) {
        defaultReturnValue = v;
    }

    public int defaultReturnValue() {
        return defaultReturnValue;
    }


    // --- entrySet() view ---

    /** 返回条目集合视图。 */
    @Override
    public Set<Map.Entry<Character, Integer>> entrySet() {
        return new EntrySet();
    }

    private static final class FastEntry
            implements Map.Entry<Character, Integer> {
        char k;
        int v;

        @Override public Character getKey()   { return k; }
        @Override public Integer getValue() { return v; }
        @Override public Integer setValue(Integer value) {
            Integer old = v;
            v = (int) value;
            return old;
        }

        @Override public String toString() {
            return k + "=" + v;
        }
    }

    private final class FastIterator
            implements Iterator<Map.Entry<Character, Integer>> {
        int pos = 0;
        boolean zeroKeyPending = containsZeroKey;
        FastEntry entry = new FastEntry();

        {
            while (pos <= mask && !(keys[pos] != '\0')) pos++;
        }

        @Override
        public boolean hasNext() {
            return zeroKeyPending || pos <= mask;
        }

        @Override
        public Map.Entry<Character, Integer> next() {
            if (!hasNext()) throw new NoSuchElementException();
            if (zeroKeyPending) {
                zeroKeyPending = false;
                entry.k = '\0';
                entry.v = values[values.length - 1];
            } else {
                entry.k = keys[pos];
                entry.v = values[pos];
                pos++;
                while (pos <= mask && !(keys[pos] != '\0')) pos++;
            }
            return entry;
        }
    }

    private final class EntrySet
            extends AbstractSet<Map.Entry<Character, Integer>> {
        @Override
        public Iterator<Map.Entry<Character, Integer>> iterator() {
            return new FastIterator();
        }

        @Override
        public int size() {
            return size;
        }

        @Override @SuppressWarnings("unchecked")
        public boolean contains(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Character, Integer> e = (Map.Entry<Character, Integer>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Character)) return false;
            
            char kk = (char) (Character) k;
            if (!containsKey(kk)) return false;
            int v = get(kk);
            return Objects.equals(v, e.getValue());
        }

        @Override @SuppressWarnings("unchecked")
        public boolean remove(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Character, Integer> e = (Map.Entry<Character, Integer>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Character)) return false;
            
            char kk = (char) (Character) k;
            if (!containsKey(kk)) return false;
            int v = get(kk);
            if (!Objects.equals(v, e.getValue())) return false;
            Char2IntFastHashMap.this.remove(kk);
            return true;
        }
    }


    // --- private helpers (unchanged) ---

    private void tryShrink() {
        int capacity = keys.length - 1;
        if (capacity <= minCapacity) return;
        if (capacity <= 16) return;
        if (size > maxOccupied / 4) return;

        int newCapacity = Math.max(minCapacity, capacity / 2);
        rehash(newCapacity);
    }

    private void shiftKeys(int pos) {
        int hole = pos;
        int scan = pos;
        char[] key = this.keys;
        int[] value = this.values;

        while (true) {
            scan = (scan + 1) & mask;

            char _v = key[scan];
            if (_v == '\0') {
                key[hole] = '\0';
                return;
            }

            char curr = key[scan];
            int slot = hash(curr) & mask;

            if (hole <= scan ? hole >= slot || slot > scan : hole >= slot && slot > scan) {
                key[hole] = curr;
                value[hole] = value[scan];
                hole = scan;
            }
        }
    }

    private void rehash(int newCapacity) {
        char[] oldKeys = keys;
        int[] oldValues = values;
        boolean oldHasZero = containsZeroKey;
        int oldZeroVal = oldHasZero ? oldValues[oldValues.length - 1] : -1;

        int newMask = newCapacity - 1;
        keys = new char[newCapacity + 1];
        values = new int[newCapacity + 1];
        mask = newMask;
        maxOccupied = (int) (newCapacity * loadFactor);

        if (containsZeroKey) {
            values[keys.length - 1] = oldZeroVal;
        }

        for (int i = 0; i < oldKeys.length - 1; i++) {
            char _v = oldKeys[i];
            if (!(_v == '\0')) {
                int pos = hash(oldKeys[i]) & mask;
                while (keys[pos] != '\0') pos = (pos + 1) & mask;
                keys[pos] = oldKeys[i];
                values[pos] = oldValues[i];
            }
        }
    }

    private static int hash(char key) {
        long k2 = key;
        return (int) HashUtil.goldenHash(k2);
    }

    private static int tableSize(int n) {
        int p = 1;
        while (p < n) p <<= 1;
        return Math.max(p, 16);
    }
}
