/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/FastHashMap.ramet" and regenerate instead.
 */

package com.flora.fast.container.map;

import com.flora.tag.ThreadFragile;
import com.flora.entropy.HashUtil;
import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.flora.fast.container.consumer.*;
/**
 * Long→Object 类型专用开地址哈希映射。
 * <p>使用开放寻址法 + 线性探测，零值作为空槽标记。
 * 避免装箱拆箱开销，适合高性能场景。</p>
 *
 * @param <K> 键类型
 * @param <V> 值类型
 */
@ThreadFragile
public class Long2ObjectFastHashMap
    extends AbstractMap<Long, Object> {

    private long[] keys;
    private Object[] values;
    private int size;
    private int mask;
    private boolean containsZeroKey;
    private final float loadFactor;
    private int maxOccupied;
    private final int minCapacity;
    private Object defaultReturnValue = null;


    /** 创建默认容量(16)、默认负载因子(0.75)的映射。 */
    public Long2ObjectFastHashMap() {
        this(16, 0.75f);
    }

    public Long2ObjectFastHashMap(int initialCapacity) {
        this(initialCapacity, 0.75f);
    }

    public Long2ObjectFastHashMap(int initialCapacity, float loadFactor) {
        if (initialCapacity <= 0) throw new IllegalArgumentException("Capacity must be positive");
        if (loadFactor <= 0 || loadFactor >= 1) throw new IllegalArgumentException("Load factor must be in (0, 1)");
        int capacity = tableSize(initialCapacity);
        this.keys = new long[capacity + 1];
        this.values = new Object[capacity + 1];
        this.mask = capacity - 1;
        this.loadFactor = loadFactor;
        this.maxOccupied = (int) (capacity * loadFactor);
        this.minCapacity = capacity;
    }

    // --- primitive K: add Map.get(Object) etc. delegating via cast ---

    /** 是否包含指定键。 */
    public boolean containsKey(long key) {
        if (key == 0L) return containsZeroKey;
        int pos = hash(key) & mask;
        while (keys[pos] != 0L) {
            if (keys[pos] == key) return true;
            pos = (pos + 1) & mask;
        }
        return false;
    }

    @Override
    public boolean containsKey(Object key) {
        if (!(key instanceof Long)) return false;
        return containsKey((long) (Long) key);
    }

    /** 获取键对应的值。@return 值或默认返回值 */
    public Object get(long key) {
        return getOrDefault(key, defaultReturnValue);
    }

    @Override
    public Object get(Object key) {
        if (!(key instanceof Long)) return null;
        long kk = (long) (Long) key;
        if (!containsKey(kk)) return null;
        return get(kk);
    }

    public Object getOrDefault(long key, Object defaultValue) {
        if (key == 0L) return containsZeroKey ? values[values.length - 1] : defaultValue;
        int pos = hash(key) & mask;
        while (keys[pos] != 0L) {
            if (keys[pos] == key) return values[pos];
            pos = (pos + 1) & mask;
        }
        return defaultValue;
    }

    /** 放入键值对。@return 旧值或默认返回值 */
    public Object put(long key, Object value) {
        if (key == 0L) {
            if (containsZeroKey) {
                Object old = values[values.length - 1];
                values[values.length - 1] = value;
                return old;
            }
            containsZeroKey = true;
            values[values.length - 1] = value;
            size++;
            if (size > maxOccupied) rehash(tableSize(values.length));
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != 0L) {
            if (keys[pos] == key) {
                Object old = values[pos];
                values[pos] = value;
                return old;
            }
            pos = (pos + 1) & mask;
        }
        keys[pos] = key;
        values[pos] = value;
        size++;
        if (size > maxOccupied) rehash(tableSize(values.length));
        return defaultReturnValue;
    }

    @Override
    public Object put(Long key, Object value) {
        long kk = (long) key;
        Object vv = (Object) value;
        if (!containsKey(kk)) {
            put(kk, vv);
            return null;
        }
        return put(kk, vv);
    }

    /** 移除键值对。@return 旧值或默认返回值 */
    public Object remove(long key) {
        if (key == 0L) {
            if (containsZeroKey) {
                Object old = values[values.length - 1];
                containsZeroKey = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != 0L) {
            if (keys[pos] == key) {
                Object old = values[pos];
                keys[pos] = 0L;
                size--;
                shiftKeys(pos);
                tryShrink();
                return old;
            }
            pos = (pos + 1) & mask;
        }
        return defaultReturnValue;
    }

    @Override
    public Object remove(Object key) {
        if (!(key instanceof Long)) return null;
        long kk = (long) (Long) key;
        if (!containsKey(kk)) return null;
        return remove(kk);
    }
    /** 清空映射。 */
    public void clear() {
        Arrays.fill(keys, 0L);
        containsZeroKey = false;
        size = 0;
    }

    /** 返回条目数。 */
    public int size() {
        return size;
    }

    /** 映射是否为空。 */
    public boolean isEmpty() {
        return size == 0;
    }

    /** 遍历所有键值对。@param action 消费接口 */
    public void forEach(Long2ObjectConsumer action) {
        for (int pos = 0; pos <= mask; pos++) {
            if (!(keys[pos] != 0L)) continue;
            action.accept(keys[pos], values[pos]);
        }
        if (containsZeroKey) action.accept(0L, values[values.length - 1]);
    }

    public void defaultReturnValue(Object v) {
        defaultReturnValue = v;
    }

    public Object defaultReturnValue() {
        return defaultReturnValue;
    }


    // --- entrySet() view ---

    /** 返回条目集合视图。 */
    @Override
    public Set<Map.Entry<Long, Object>> entrySet() {
        return new EntrySet();
    }

    private static final class FastEntry
            implements Map.Entry<Long, Object> {
        long k;
        Object v;

        @Override public Long getKey()   { return k; }
        @Override public Object getValue() { return v; }
        @Override public Object setValue(Object value) {
            Object old = v;
            v = (Object) value;
            return old;
        }

        @Override public String toString() {
            return k + "=" + v;
        }
    }

    private final class FastIterator
            implements Iterator<Map.Entry<Long, Object>> {
        int pos = 0;
        boolean zeroKeyPending = containsZeroKey;
        FastEntry entry = new FastEntry();

        {
            while (pos <= mask && !(keys[pos] != 0L)) pos++;
        }

        @Override
        public boolean hasNext() {
            return zeroKeyPending || pos <= mask;
        }

        @Override
        public Map.Entry<Long, Object> next() {
            if (!hasNext()) throw new NoSuchElementException();
            if (zeroKeyPending) {
                zeroKeyPending = false;
                entry.k = 0L;
                entry.v = values[values.length - 1];
            } else {
                entry.k = keys[pos];
                entry.v = values[pos];
                pos++;
                while (pos <= mask && !(keys[pos] != 0L)) pos++;
            }
            return entry;
        }
    }

    private final class EntrySet
            extends AbstractSet<Map.Entry<Long, Object>> {
        @Override
        public Iterator<Map.Entry<Long, Object>> iterator() {
            return new FastIterator();
        }

        @Override
        public int size() {
            return size;
        }

        @Override @SuppressWarnings("unchecked")
        public boolean contains(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Long, Object> e = (Map.Entry<Long, Object>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Long)) return false;
            
            long kk = (long) (Long) k;
            if (!containsKey(kk)) return false;
            Object v = get(kk);
            return Objects.equals(v, e.getValue());
        }

        @Override @SuppressWarnings("unchecked")
        public boolean remove(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Long, Object> e = (Map.Entry<Long, Object>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Long)) return false;
            
            long kk = (long) (Long) k;
            if (!containsKey(kk)) return false;
            Object v = get(kk);
            if (!Objects.equals(v, e.getValue())) return false;
            Long2ObjectFastHashMap.this.remove(kk);
            return true;
        }
    }


    // --- private helpers (unchanged) ---

    private void tryShrink() {
        int capacity = keys.length - 1;
        if (capacity <= minCapacity) return;
        if (capacity <= 16) return;
        if (size > maxOccupied / 4) return;

        int newCapacity = Math.max(minCapacity, capacity / 2);
        rehash(newCapacity);
    }

    private void shiftKeys(int pos) {
        int hole = pos;
        int scan = pos;
        long[] key = this.keys;
        Object[] value = this.values;

        while (true) {
            scan = (scan + 1) & mask;

            long _v = key[scan];
            if (_v == 0L) {
                key[hole] = 0L;
                return;
            }

            long curr = key[scan];
            int slot = hash(curr) & mask;

            if (hole <= scan ? hole >= slot || slot > scan : hole >= slot && slot > scan) {
                key[hole] = curr;
                value[hole] = value[scan];
                hole = scan;
            }
        }
    }

    private void rehash(int newCapacity) {
        long[] oldKeys = keys;
        Object[] oldValues = values;
        boolean oldHasZero = containsZeroKey;
        Object oldZeroVal = oldHasZero ? oldValues[oldValues.length - 1] : null;

        int newMask = newCapacity - 1;
        keys = new long[newCapacity + 1];
        values = new Object[newCapacity + 1];
        mask = newMask;
        maxOccupied = (int) (newCapacity * loadFactor);

        if (containsZeroKey) {
            values[keys.length - 1] = oldZeroVal;
        }

        for (int i = 0; i < oldKeys.length - 1; i++) {
            long _v = oldKeys[i];
            if (!(_v == 0L)) {
                int pos = hash(oldKeys[i]) & mask;
                while (keys[pos] != 0L) pos = (pos + 1) & mask;
                keys[pos] = oldKeys[i];
                values[pos] = oldValues[i];
            }
        }
    }

    private static int hash(long key) {
        long k2 = key;
        return (int) HashUtil.goldenHash(k2);
    }

    private static int tableSize(int n) {
        int p = 1;
        while (p < n) p <<= 1;
        return Math.max(p, 16);
    }
}
