/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/FastHashMap.ramet" and regenerate instead.
 */

package com.flora.fast.container.map;

import com.flora.tag.ThreadFragile;
import com.flora.entropy.HashUtil;
import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.flora.fast.container.consumer.*;
/**
 * Object→Short 类型专用开地址哈希映射。
 * <p>使用开放寻址法 + 线性探测，零值作为空槽标记。
 * 避免装箱拆箱开销，适合高性能场景。</p>
 *
 * @param <K> 键类型
 * @param <V> 值类型
 */
@ThreadFragile
public class Object2ShortFastHashMap
    extends AbstractMap<Object, Short> {

    private Object[] keys;
    private short[] values;
    private int size;
    private int mask;
    private boolean containsZeroKey;
    private final float loadFactor;
    private int maxOccupied;
    private final int minCapacity;
    private short defaultReturnValue = (short)-1;


    /** 创建默认容量(16)、默认负载因子(0.75)的映射。 */
    public Object2ShortFastHashMap() {
        this(16, 0.75f);
    }

    public Object2ShortFastHashMap(int initialCapacity) {
        this(initialCapacity, 0.75f);
    }

    public Object2ShortFastHashMap(int initialCapacity, float loadFactor) {
        if (initialCapacity <= 0) throw new IllegalArgumentException("Capacity must be positive");
        if (loadFactor <= 0 || loadFactor >= 1) throw new IllegalArgumentException("Load factor must be in (0, 1)");
        int capacity = tableSize(initialCapacity);
        this.keys = new Object[capacity + 1];
        this.values = new short[capacity + 1];
        this.mask = capacity - 1;
        this.loadFactor = loadFactor;
        this.maxOccupied = (int) (capacity * loadFactor);
        this.minCapacity = capacity;
    }

    
    // --- raw methods for Object-key + primitive-value ---

    /** 是否包含指定键。 */
    public boolean containsKey(Object key) {
        if (key == null) return containsZeroKey;
        int pos = hash(key) & mask;
        while (keys[pos] != null) {
            if (Objects.equals(keys[pos], key)) return true;
            pos = (pos + 1) & mask;
        }
        return false;
    }

    public short getRaw(Object key) {
        return getOrDefault(key, defaultReturnValue);
    }

    /** 获取键对应的值。@return 值或默认返回值 */
    @Override
    public Short get(Object key) {
        if (!containsKey(key)) return null;
        return getRaw(key);
    }

    public short getOrDefault(Object key, short defaultValue) {
        if (key == null) return containsZeroKey ? values[values.length - 1] : defaultValue;
        int pos = hash(key) & mask;
        while (keys[pos] != null) {
            if (Objects.equals(keys[pos], key)) return values[pos];
            pos = (pos + 1) & mask;
        }
        return defaultValue;
    }

    public short putRaw(Object key, short value) {
        if (key == null) {
            if (containsZeroKey) {
                short old = values[values.length - 1];
                values[values.length - 1] = value;
                return old;
            }
            containsZeroKey = true;
            values[values.length - 1] = value;
            size++;
            if (size > maxOccupied) rehash(tableSize(values.length));
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != null) {
            if (Objects.equals(keys[pos], key)) {
                short old = values[pos];
                values[pos] = value;
                return old;
            }
            pos = (pos + 1) & mask;
        }
        keys[pos] = (Object) key;
        values[pos] = value;
        size++;
        if (size > maxOccupied) rehash(tableSize(values.length));
        return defaultReturnValue;
    }

    /** 放入键值对。@return 旧值或默认返回值 */
    @Override
    public Short put(Object key, Short value) {
        if (!containsKey(key)) {
            putRaw(key, (short) value);
            return null;
        }
        return putRaw(key, (short) value);
    }

    public short removeRaw(Object key) {
        if (key == null) {
            if (containsZeroKey) {
                short old = values[values.length - 1];
                containsZeroKey = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != null) {
            if (Objects.equals(keys[pos], key)) {
                short old = values[pos];
                keys[pos] = null;
                size--;
                shiftKeys(pos);
                tryShrink();
                return old;
            }
            pos = (pos + 1) & mask;
        }
        return defaultReturnValue;
    }

    /** 移除键值对。@return 旧值或默认返回值 */
    @Override
    public Short remove(Object key) {
        if (!containsKey(key)) return null;
        return removeRaw(key);
    }

    
    /** 清空映射。 */
    public void clear() {
        Arrays.fill(keys, null);
        containsZeroKey = false;
        size = 0;
    }

    /** 返回条目数。 */
    public int size() {
        return size;
    }

    /** 映射是否为空。 */
    public boolean isEmpty() {
        return size == 0;
    }

    /** 遍历所有键值对。@param action 消费接口 */
    public void forEach(Object2ShortConsumer action) {
        for (int pos = 0; pos <= mask; pos++) {
            if (!(keys[pos] != null)) continue;
            action.accept(keys[pos], values[pos]);
        }
        if (containsZeroKey) action.accept(null, values[values.length - 1]);
    }

    public void defaultReturnValue(short v) {
        defaultReturnValue = v;
    }

    public short defaultReturnValue() {
        return defaultReturnValue;
    }


    // --- entrySet() view ---

    /** 返回条目集合视图。 */
    @Override
    public Set<Map.Entry<Object, Short>> entrySet() {
        return new EntrySet();
    }

    private static final class FastEntry
            implements Map.Entry<Object, Short> {
        Object k;
        short v;

        @Override public Object getKey()   { return k; }
        @Override public Short getValue() { return v; }
        @Override public Short setValue(Short value) {
            Short old = v;
            v = (short) value;
            return old;
        }

        @Override public String toString() {
            return k + "=" + v;
        }
    }

    private final class FastIterator
            implements Iterator<Map.Entry<Object, Short>> {
        int pos = 0;
        boolean zeroKeyPending = containsZeroKey;
        FastEntry entry = new FastEntry();

        {
            while (pos <= mask && !(keys[pos] != null)) pos++;
        }

        @Override
        public boolean hasNext() {
            return zeroKeyPending || pos <= mask;
        }

        @Override
        public Map.Entry<Object, Short> next() {
            if (!hasNext()) throw new NoSuchElementException();
            if (zeroKeyPending) {
                zeroKeyPending = false;
                entry.k = null;
                entry.v = values[values.length - 1];
            } else {
                entry.k = keys[pos];
                entry.v = values[pos];
                pos++;
                while (pos <= mask && !(keys[pos] != null)) pos++;
            }
            return entry;
        }
    }

    private final class EntrySet
            extends AbstractSet<Map.Entry<Object, Short>> {
        @Override
        public Iterator<Map.Entry<Object, Short>> iterator() {
            return new FastIterator();
        }

        @Override
        public int size() {
            return size;
        }

        @Override @SuppressWarnings("unchecked")
        public boolean contains(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Object, Short> e = (Map.Entry<Object, Short>) o;
            Object k = e.getKey();
            
            Object kk = (Object) (Object) k;
            if (!containsKey(kk)) return false;
            short v = get(kk);
            return Objects.equals(v, e.getValue());
        }

        @Override @SuppressWarnings("unchecked")
        public boolean remove(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Object, Short> e = (Map.Entry<Object, Short>) o;
            Object k = e.getKey();
            
            Object kk = (Object) (Object) k;
            if (!containsKey(kk)) return false;
            short v = get(kk);
            if (!Objects.equals(v, e.getValue())) return false;
            Object2ShortFastHashMap.this.remove(kk);
            return true;
        }
    }


    // --- private helpers (unchanged) ---

    private void tryShrink() {
        int capacity = keys.length - 1;
        if (capacity <= minCapacity) return;
        if (capacity <= 16) return;
        if (size > maxOccupied / 4) return;

        int newCapacity = Math.max(minCapacity, capacity / 2);
        rehash(newCapacity);
    }

    private void shiftKeys(int pos) {
        int hole = pos;
        int scan = pos;
        Object[] key = this.keys;
        short[] value = this.values;

        while (true) {
            scan = (scan + 1) & mask;

            Object _v = key[scan];
            if (_v == null) {
                key[hole] = null;
                return;
            }

            Object curr = key[scan];
            int slot = hash(curr) & mask;

            if (hole <= scan ? hole >= slot || slot > scan : hole >= slot && slot > scan) {
                key[hole] = curr;
                value[hole] = value[scan];
                hole = scan;
            }
        }
    }

    private void rehash(int newCapacity) {
        Object[] oldKeys = keys;
        short[] oldValues = values;
        boolean oldHasZero = containsZeroKey;
        short oldZeroVal = oldHasZero ? oldValues[oldValues.length - 1] : (short)-1;

        int newMask = newCapacity - 1;
        keys = new Object[newCapacity + 1];
        values = new short[newCapacity + 1];
        mask = newMask;
        maxOccupied = (int) (newCapacity * loadFactor);

        if (containsZeroKey) {
            values[keys.length - 1] = oldZeroVal;
        }

        for (int i = 0; i < oldKeys.length - 1; i++) {
            Object _v = oldKeys[i];
            if (!(_v == null)) {
                int pos = hash(oldKeys[i]) & mask;
                while (keys[pos] != null) pos = (pos + 1) & mask;
                keys[pos] = oldKeys[i];
                values[pos] = oldValues[i];
            }
        }
    }

    private static int hash(Object key) {
        return HashUtil.goldenHash((key == null) ? 0 : key.hashCode());
    }

    private static int tableSize(int n) {
        int p = 1;
        while (p < n) p <<= 1;
        return Math.max(p, 16);
    }
}
