/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/FastHashMap.ramet" and regenerate instead.
 */

package com.flora.fast.container.map;

import com.flora.tag.ThreadFragile;
import com.flora.entropy.HashUtil;
import java.util.AbstractMap;
import java.util.AbstractSet;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.flora.fast.container.consumer.*;
/**
 * Short→Char 类型专用开地址哈希映射。
 * <p>使用开放寻址法 + 线性探测，零值作为空槽标记。
 * 避免装箱拆箱开销，适合高性能场景。</p>
 *
 * @param <K> 键类型
 * @param <V> 值类型
 */
@ThreadFragile
public class Short2CharFastHashMap
    extends AbstractMap<Short, Character> {

    private short[] keys;
    private char[] values;
    private int size;
    private int mask;
    private boolean containsZeroKey;
    private final float loadFactor;
    private int maxOccupied;
    private final int minCapacity;
    private char defaultReturnValue = '\u0000';


    /** 创建默认容量(16)、默认负载因子(0.75)的映射。 */
    public Short2CharFastHashMap() {
        this(16, 0.75f);
    }

    public Short2CharFastHashMap(int initialCapacity) {
        this(initialCapacity, 0.75f);
    }

    public Short2CharFastHashMap(int initialCapacity, float loadFactor) {
        if (initialCapacity <= 0) throw new IllegalArgumentException("Capacity must be positive");
        if (loadFactor <= 0 || loadFactor >= 1) throw new IllegalArgumentException("Load factor must be in (0, 1)");
        int capacity = tableSize(initialCapacity);
        this.keys = new short[capacity + 1];
        this.values = new char[capacity + 1];
        this.mask = capacity - 1;
        this.loadFactor = loadFactor;
        this.maxOccupied = (int) (capacity * loadFactor);
        this.minCapacity = capacity;
    }

    // --- primitive K: add Map.get(Object) etc. delegating via cast ---

    /** 是否包含指定键。 */
    public boolean containsKey(short key) {
        if (key == (short)0) return containsZeroKey;
        int pos = hash(key) & mask;
        while (keys[pos] != (short)0) {
            if (keys[pos] == key) return true;
            pos = (pos + 1) & mask;
        }
        return false;
    }

    @Override
    public boolean containsKey(Object key) {
        if (!(key instanceof Short)) return false;
        return containsKey((short) (Short) key);
    }

    /** 获取键对应的值。@return 值或默认返回值 */
    public char get(short key) {
        return getOrDefault(key, defaultReturnValue);
    }

    @Override
    public Character get(Object key) {
        if (!(key instanceof Short)) return null;
        short kk = (short) (Short) key;
        if (!containsKey(kk)) return null;
        return get(kk);
    }

    public char getOrDefault(short key, char defaultValue) {
        if (key == (short)0) return containsZeroKey ? values[values.length - 1] : defaultValue;
        int pos = hash(key) & mask;
        while (keys[pos] != (short)0) {
            if (keys[pos] == key) return values[pos];
            pos = (pos + 1) & mask;
        }
        return defaultValue;
    }

    /** 放入键值对。@return 旧值或默认返回值 */
    public char put(short key, char value) {
        if (key == (short)0) {
            if (containsZeroKey) {
                char old = values[values.length - 1];
                values[values.length - 1] = value;
                return old;
            }
            containsZeroKey = true;
            values[values.length - 1] = value;
            size++;
            if (size > maxOccupied) rehash(tableSize(values.length));
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != (short)0) {
            if (keys[pos] == key) {
                char old = values[pos];
                values[pos] = value;
                return old;
            }
            pos = (pos + 1) & mask;
        }
        keys[pos] = key;
        values[pos] = value;
        size++;
        if (size > maxOccupied) rehash(tableSize(values.length));
        return defaultReturnValue;
    }

    @Override
    public Character put(Short key, Character value) {
        short kk = (short) key;
        char vv = (char) value;
        if (!containsKey(kk)) {
            put(kk, vv);
            return null;
        }
        return put(kk, vv);
    }

    /** 移除键值对。@return 旧值或默认返回值 */
    public char remove(short key) {
        if (key == (short)0) {
            if (containsZeroKey) {
                char old = values[values.length - 1];
                containsZeroKey = false;
                size--;
                tryShrink();
                return old;
            }
            return defaultReturnValue;
        }

        int pos = hash(key) & mask;
        while (keys[pos] != (short)0) {
            if (keys[pos] == key) {
                char old = values[pos];
                keys[pos] = (short)0;
                size--;
                shiftKeys(pos);
                tryShrink();
                return old;
            }
            pos = (pos + 1) & mask;
        }
        return defaultReturnValue;
    }

    @Override
    public Character remove(Object key) {
        if (!(key instanceof Short)) return null;
        short kk = (short) (Short) key;
        if (!containsKey(kk)) return null;
        return remove(kk);
    }
    /** 清空映射。 */
    public void clear() {
        Arrays.fill(keys, (short)0);
        containsZeroKey = false;
        size = 0;
    }

    /** 返回条目数。 */
    public int size() {
        return size;
    }

    /** 映射是否为空。 */
    public boolean isEmpty() {
        return size == 0;
    }

    /** 遍历所有键值对。@param action 消费接口 */
    public void forEach(Short2CharConsumer action) {
        for (int pos = 0; pos <= mask; pos++) {
            if (!(keys[pos] != (short)0)) continue;
            action.accept(keys[pos], values[pos]);
        }
        if (containsZeroKey) action.accept((short)0, values[values.length - 1]);
    }

    public void defaultReturnValue(char v) {
        defaultReturnValue = v;
    }

    public char defaultReturnValue() {
        return defaultReturnValue;
    }


    // --- entrySet() view ---

    /** 返回条目集合视图。 */
    @Override
    public Set<Map.Entry<Short, Character>> entrySet() {
        return new EntrySet();
    }

    private static final class FastEntry
            implements Map.Entry<Short, Character> {
        short k;
        char v;

        @Override public Short getKey()   { return k; }
        @Override public Character getValue() { return v; }
        @Override public Character setValue(Character value) {
            Character old = v;
            v = (char) value;
            return old;
        }

        @Override public String toString() {
            return k + "=" + v;
        }
    }

    private final class FastIterator
            implements Iterator<Map.Entry<Short, Character>> {
        int pos = 0;
        boolean zeroKeyPending = containsZeroKey;
        FastEntry entry = new FastEntry();

        {
            while (pos <= mask && !(keys[pos] != (short)0)) pos++;
        }

        @Override
        public boolean hasNext() {
            return zeroKeyPending || pos <= mask;
        }

        @Override
        public Map.Entry<Short, Character> next() {
            if (!hasNext()) throw new NoSuchElementException();
            if (zeroKeyPending) {
                zeroKeyPending = false;
                entry.k = (short)0;
                entry.v = values[values.length - 1];
            } else {
                entry.k = keys[pos];
                entry.v = values[pos];
                pos++;
                while (pos <= mask && !(keys[pos] != (short)0)) pos++;
            }
            return entry;
        }
    }

    private final class EntrySet
            extends AbstractSet<Map.Entry<Short, Character>> {
        @Override
        public Iterator<Map.Entry<Short, Character>> iterator() {
            return new FastIterator();
        }

        @Override
        public int size() {
            return size;
        }

        @Override @SuppressWarnings("unchecked")
        public boolean contains(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Short, Character> e = (Map.Entry<Short, Character>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Short)) return false;
            
            short kk = (short) (Short) k;
            if (!containsKey(kk)) return false;
            char v = get(kk);
            return Objects.equals(v, e.getValue());
        }

        @Override @SuppressWarnings("unchecked")
        public boolean remove(Object o) {
            if (!(o instanceof Map.Entry)) return false;
            Map.Entry<Short, Character> e = (Map.Entry<Short, Character>) o;
            Object k = e.getKey();
            
            if (!(k instanceof Short)) return false;
            
            short kk = (short) (Short) k;
            if (!containsKey(kk)) return false;
            char v = get(kk);
            if (!Objects.equals(v, e.getValue())) return false;
            Short2CharFastHashMap.this.remove(kk);
            return true;
        }
    }


    // --- private helpers (unchanged) ---

    private void tryShrink() {
        int capacity = keys.length - 1;
        if (capacity <= minCapacity) return;
        if (capacity <= 16) return;
        if (size > maxOccupied / 4) return;

        int newCapacity = Math.max(minCapacity, capacity / 2);
        rehash(newCapacity);
    }

    private void shiftKeys(int pos) {
        int hole = pos;
        int scan = pos;
        short[] key = this.keys;
        char[] value = this.values;

        while (true) {
            scan = (scan + 1) & mask;

            short _v = key[scan];
            if (_v == (short)0) {
                key[hole] = (short)0;
                return;
            }

            short curr = key[scan];
            int slot = hash(curr) & mask;

            if (hole <= scan ? hole >= slot || slot > scan : hole >= slot && slot > scan) {
                key[hole] = curr;
                value[hole] = value[scan];
                hole = scan;
            }
        }
    }

    private void rehash(int newCapacity) {
        short[] oldKeys = keys;
        char[] oldValues = values;
        boolean oldHasZero = containsZeroKey;
        char oldZeroVal = oldHasZero ? oldValues[oldValues.length - 1] : '\u0000';

        int newMask = newCapacity - 1;
        keys = new short[newCapacity + 1];
        values = new char[newCapacity + 1];
        mask = newMask;
        maxOccupied = (int) (newCapacity * loadFactor);

        if (containsZeroKey) {
            values[keys.length - 1] = oldZeroVal;
        }

        for (int i = 0; i < oldKeys.length - 1; i++) {
            short _v = oldKeys[i];
            if (!(_v == (short)0)) {
                int pos = hash(oldKeys[i]) & mask;
                while (keys[pos] != (short)0) pos = (pos + 1) & mask;
                keys[pos] = oldKeys[i];
                values[pos] = oldValues[i];
            }
        }
    }

    private static int hash(short key) {
        return HashUtil.goldenHash((int) key);
    }

    private static int tableSize(int n) {
        int p = 1;
        while (p < n) p <<= 1;
        return Math.max(p, 16);
    }
}
