/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastTuple/FastTupleXXX.ramet" and regenerate instead.
 */

package com.flora.fast.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;
import java.io.Serializable;

/**
 * 原始类型特化的快速元组。
 * <p>避免装箱开销，提供对原始类型元素的高效存储和访问。</p>
 */
@ReadOnly
public final class FastTupleIIFF implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    /** 第1个元素 */
    private final int v1;
    /** 第2个元素 */
    private final int v2;
    /** 第3个元素 */
    private final float v3;
    /** 第4个元素 */
    private final float v4;
    /**
     * 创建一个包含指定原始类型元素的快速元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     */
    public FastTupleIIFF(int v1,int v2,float v3,float v4){
        this.v1 = v1;
        this.v2 = v2;
        this.v3 = v3;
        this.v4 = v4;
    }

    /**
     * 返回第1个元素。
     *
     * @return 第1个元素
     */
    public int getI1() { return v1; }
    /**
     * 返回第2个元素。
     *
     * @return 第2个元素
     */
    public int getI2() { return v2; }
    /**
     * 返回第3个元素。
     *
     * @return 第3个元素
     */
    public float getF1() { return v3; }
    /**
     * 返回第4个元素。
     *
     * @return 第4个元素
     */
    public float getF2() { return v4; }
    /**
     * 比较此快速元组与指定对象是否相等。
     *
     * @param o 要比较的对象
     * @return 如果所有元素值相等则返回 true
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FastTupleIIFF that)) return false;
        return this.v1 == that.v1
            && this.v2 == that.v2
            && Float.compare(this.v3, that.v3) == 0
            && Float.compare(this.v4, that.v4) == 0;
    }

    /**
     * 返回此快速元组的哈希码。
     *
     * @return 哈希码值
     */
    @Override
    public int hashCode() {
        int result = Integer.hashCode(v1);
        result = 31 * result + Integer.hashCode(v2);
        result = 31 * result + Float.hashCode(v3);
        result = 31 * result + Float.hashCode(v4);
        return result;
    }

    /**
     * 返回此快速元组的字符串表示。
     * <p>格式为 {@code <v1, v2, ...>}。</p>
     *
     * @return 字符串表示
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("<");
        sb.append(v1).append(", ");
        sb.append(v2).append(", ");
        sb.append(v3).append(", ");
        sb.append(v4);
        return sb.append(">").toString();
    }
}
