/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastTuple/FastTuple.ramet" and regenerate instead.
 */

package com.flora.fast.container.tuple;

public final class FastTuple {
    private FastTuple() {}
    
    /** 创建 FastTupleII 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleII 实例
     */
    public static FastTupleII of(int v1, int v2){
        return new FastTupleII(v1, v2);
    }
    
    /** 创建 FastTupleIL 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleIL 实例
     */
    public static FastTupleIL of(int v1, long v2){
        return new FastTupleIL(v1, v2);
    }
    
    /** 创建 FastTupleIL 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleIL 实例
     */
    public static FastTupleIL of(long v1, int v2){
        return new FastTupleIL(v2, v1);
    }
    
    /** 创建 FastTupleIF 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleIF 实例
     */
    public static FastTupleIF of(int v1, float v2){
        return new FastTupleIF(v1, v2);
    }
    
    /** 创建 FastTupleIF 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleIF 实例
     */
    public static FastTupleIF of(float v1, int v2){
        return new FastTupleIF(v2, v1);
    }
    
    /** 创建 FastTupleID 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleID 实例
     */
    public static FastTupleID of(int v1, double v2){
        return new FastTupleID(v1, v2);
    }
    
    /** 创建 FastTupleID 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleID 实例
     */
    public static FastTupleID of(double v1, int v2){
        return new FastTupleID(v2, v1);
    }
    
    /** 创建 FastTupleIB 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleIB 实例
     */
    public static FastTupleIB of(int v1, byte v2){
        return new FastTupleIB(v1, v2);
    }
    
    /** 创建 FastTupleIB 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleIB 实例
     */
    public static FastTupleIB of(byte v1, int v2){
        return new FastTupleIB(v2, v1);
    }
    
    /** 创建 FastTupleIC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleIC 实例
     */
    public static FastTupleIC of(int v1, char v2){
        return new FastTupleIC(v1, v2);
    }
    
    /** 创建 FastTupleIC 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleIC 实例
     */
    public static FastTupleIC of(char v1, int v2){
        return new FastTupleIC(v2, v1);
    }
    
    /** 创建 FastTupleIZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleIZ 实例
     */
    public static FastTupleIZ of(int v1, boolean v2){
        return new FastTupleIZ(v1, v2);
    }
    
    /** 创建 FastTupleIZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleIZ 实例
     */
    public static FastTupleIZ of(boolean v1, int v2){
        return new FastTupleIZ(v2, v1);
    }
    
    /** 创建 FastTupleLL 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLL 实例
     */
    public static FastTupleLL of(long v1, long v2){
        return new FastTupleLL(v1, v2);
    }
    
    /** 创建 FastTupleLF 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLF 实例
     */
    public static FastTupleLF of(long v1, float v2){
        return new FastTupleLF(v1, v2);
    }
    
    /** 创建 FastTupleLF 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleLF 实例
     */
    public static FastTupleLF of(float v1, long v2){
        return new FastTupleLF(v2, v1);
    }
    
    /** 创建 FastTupleLD 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLD 实例
     */
    public static FastTupleLD of(long v1, double v2){
        return new FastTupleLD(v1, v2);
    }
    
    /** 创建 FastTupleLD 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleLD 实例
     */
    public static FastTupleLD of(double v1, long v2){
        return new FastTupleLD(v2, v1);
    }
    
    /** 创建 FastTupleLB 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLB 实例
     */
    public static FastTupleLB of(long v1, byte v2){
        return new FastTupleLB(v1, v2);
    }
    
    /** 创建 FastTupleLB 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleLB 实例
     */
    public static FastTupleLB of(byte v1, long v2){
        return new FastTupleLB(v2, v1);
    }
    
    /** 创建 FastTupleLC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLC 实例
     */
    public static FastTupleLC of(long v1, char v2){
        return new FastTupleLC(v1, v2);
    }
    
    /** 创建 FastTupleLC 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleLC 实例
     */
    public static FastTupleLC of(char v1, long v2){
        return new FastTupleLC(v2, v1);
    }
    
    /** 创建 FastTupleLZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleLZ 实例
     */
    public static FastTupleLZ of(long v1, boolean v2){
        return new FastTupleLZ(v1, v2);
    }
    
    /** 创建 FastTupleLZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleLZ 实例
     */
    public static FastTupleLZ of(boolean v1, long v2){
        return new FastTupleLZ(v2, v1);
    }
    
    /** 创建 FastTupleFF 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleFF 实例
     */
    public static FastTupleFF of(float v1, float v2){
        return new FastTupleFF(v1, v2);
    }
    
    /** 创建 FastTupleFD 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleFD 实例
     */
    public static FastTupleFD of(float v1, double v2){
        return new FastTupleFD(v1, v2);
    }
    
    /** 创建 FastTupleFD 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleFD 实例
     */
    public static FastTupleFD of(double v1, float v2){
        return new FastTupleFD(v2, v1);
    }
    
    /** 创建 FastTupleFB 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleFB 实例
     */
    public static FastTupleFB of(float v1, byte v2){
        return new FastTupleFB(v1, v2);
    }
    
    /** 创建 FastTupleFB 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleFB 实例
     */
    public static FastTupleFB of(byte v1, float v2){
        return new FastTupleFB(v2, v1);
    }
    
    /** 创建 FastTupleFC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleFC 实例
     */
    public static FastTupleFC of(float v1, char v2){
        return new FastTupleFC(v1, v2);
    }
    
    /** 创建 FastTupleFC 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleFC 实例
     */
    public static FastTupleFC of(char v1, float v2){
        return new FastTupleFC(v2, v1);
    }
    
    /** 创建 FastTupleFZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleFZ 实例
     */
    public static FastTupleFZ of(float v1, boolean v2){
        return new FastTupleFZ(v1, v2);
    }
    
    /** 创建 FastTupleFZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleFZ 实例
     */
    public static FastTupleFZ of(boolean v1, float v2){
        return new FastTupleFZ(v2, v1);
    }
    
    /** 创建 FastTupleDD 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleDD 实例
     */
    public static FastTupleDD of(double v1, double v2){
        return new FastTupleDD(v1, v2);
    }
    
    /** 创建 FastTupleDB 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleDB 实例
     */
    public static FastTupleDB of(double v1, byte v2){
        return new FastTupleDB(v1, v2);
    }
    
    /** 创建 FastTupleDB 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleDB 实例
     */
    public static FastTupleDB of(byte v1, double v2){
        return new FastTupleDB(v2, v1);
    }
    
    /** 创建 FastTupleDC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleDC 实例
     */
    public static FastTupleDC of(double v1, char v2){
        return new FastTupleDC(v1, v2);
    }
    
    /** 创建 FastTupleDC 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleDC 实例
     */
    public static FastTupleDC of(char v1, double v2){
        return new FastTupleDC(v2, v1);
    }
    
    /** 创建 FastTupleDZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleDZ 实例
     */
    public static FastTupleDZ of(double v1, boolean v2){
        return new FastTupleDZ(v1, v2);
    }
    
    /** 创建 FastTupleDZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleDZ 实例
     */
    public static FastTupleDZ of(boolean v1, double v2){
        return new FastTupleDZ(v2, v1);
    }
    
    /** 创建 FastTupleBB 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleBB 实例
     */
    public static FastTupleBB of(byte v1, byte v2){
        return new FastTupleBB(v1, v2);
    }
    
    /** 创建 FastTupleBC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleBC 实例
     */
    public static FastTupleBC of(byte v1, char v2){
        return new FastTupleBC(v1, v2);
    }
    
    /** 创建 FastTupleBC 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleBC 实例
     */
    public static FastTupleBC of(char v1, byte v2){
        return new FastTupleBC(v2, v1);
    }
    
    /** 创建 FastTupleBZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleBZ 实例
     */
    public static FastTupleBZ of(byte v1, boolean v2){
        return new FastTupleBZ(v1, v2);
    }
    
    /** 创建 FastTupleBZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleBZ 实例
     */
    public static FastTupleBZ of(boolean v1, byte v2){
        return new FastTupleBZ(v2, v1);
    }
    
    /** 创建 FastTupleCC 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleCC 实例
     */
    public static FastTupleCC of(char v1, char v2){
        return new FastTupleCC(v1, v2);
    }
    
    /** 创建 FastTupleCZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleCZ 实例
     */
    public static FastTupleCZ of(char v1, boolean v2){
        return new FastTupleCZ(v1, v2);
    }
    
    /** 创建 FastTupleCZ 实例。
     * @param v1 第2个元素
     * @param v2 第1个元素
     * @return 新的 FastTupleCZ 实例
     */
    public static FastTupleCZ of(boolean v1, char v2){
        return new FastTupleCZ(v2, v1);
    }
    
    /** 创建 FastTupleZZ 实例。
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 新的 FastTupleZZ 实例
     */
    public static FastTupleZZ of(boolean v1, boolean v2){
        return new FastTupleZZ(v1, v2);
    }
}
