/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "fastHashMap/FastHashMapConsumer.ramet" and regenerate instead.
 */

package com.flora.fast.container.consumer;

/**
 * Char→Byte 类型专用消费接口。
 * <p>接收一对键值，避免装箱开销。</p>
 *
 * @see java.util.function.BiConsumer
 */
@FunctionalInterface
public interface Char2ByteConsumer {

    /**
     * 消费一对键值。
     *
     * @param key   键
     * @param value 值
     */
    void accept(char key, byte value);
}
