/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/TupleN.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;

/**
 * 包含 11 个元素的元组。
 * <p>提供类型安全的元素访问和元组操作。</p>
 * @param <T1> 第2个元素类型
 * @param <T2> 第3个元素类型
 * @param <T3> 第4个元素类型
 * @param <T4> 第5个元素类型
 * @param <T5> 第6个元素类型
 * @param <T6> 第7个元素类型
 * @param <T7> 第8个元素类型
 * @param <T8> 第9个元素类型
 * @param <T9> 第10个元素类型
 * @param <T10> 第11个元素类型
 * @param <T11> 第12个元素类型
 */
@ReadOnly
public final class Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> extends Tuple {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 创建一个包含 11 个指定元素的元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     */
    public Tuple11(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11) {
        super(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11);
    }

    /**
     * 返回第 1 个元素。
     *
     * @return 第 1 个元素
     */
    public T1 getV1() { return (T1)getVn(1); }
    /**
     * 返回第 2 个元素。
     *
     * @return 第 2 个元素
     */
    public T2 getV2() { return (T2)getVn(2); }
    /**
     * 返回第 3 个元素。
     *
     * @return 第 3 个元素
     */
    public T3 getV3() { return (T3)getVn(3); }
    /**
     * 返回第 4 个元素。
     *
     * @return 第 4 个元素
     */
    public T4 getV4() { return (T4)getVn(4); }
    /**
     * 返回第 5 个元素。
     *
     * @return 第 5 个元素
     */
    public T5 getV5() { return (T5)getVn(5); }
    /**
     * 返回第 6 个元素。
     *
     * @return 第 6 个元素
     */
    public T6 getV6() { return (T6)getVn(6); }
    /**
     * 返回第 7 个元素。
     *
     * @return 第 7 个元素
     */
    public T7 getV7() { return (T7)getVn(7); }
    /**
     * 返回第 8 个元素。
     *
     * @return 第 8 个元素
     */
    public T8 getV8() { return (T8)getVn(8); }
    /**
     * 返回第 9 个元素。
     *
     * @return 第 9 个元素
     */
    public T9 getV9() { return (T9)getVn(9); }
    /**
     * 返回第 10 个元素。
     *
     * @return 第 10 个元素
     */
    public T10 getV10() { return (T10)getVn(10); }
    /**
     * 返回第 11 个元素。
     *
     * @return 第 11 个元素
     */
    public T11 getV11() { return (T11)getVn(11); }
    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> clone() {
        return this;
    }

    /**
     * 返回替换第 1 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV1(T1 val) {
        return new Tuple11<>(val,getV2(),getV3(),getV4(),getV5(),getV6(),getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 2 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV2(T2 val) {
        return new Tuple11<>(getV1(),val,getV3(),getV4(),getV5(),getV6(),getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 3 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV3(T3 val) {
        return new Tuple11<>(getV1(),getV2(),val,getV4(),getV5(),getV6(),getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 4 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV4(T4 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),val,getV5(),getV6(),getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 5 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV5(T5 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),val,getV6(),getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 6 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV6(T6 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),val,getV7(),getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 7 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV7(T7 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),getV6(),val,getV8(),getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 8 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV8(T8 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),getV6(),getV7(),val,getV9(),getV10(),getV11());
    }
    /**
     * 返回替换第 9 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV9(T9 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),getV6(),getV7(),getV8(),val,getV10(),getV11());
    }
    /**
     * 返回替换第 10 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV10(T10 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),getV6(),getV7(),getV8(),getV9(),val,getV11());
    }
    /**
     * 返回替换第 11 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> withV11(T11 val) {
        return new Tuple11<>(getV1(),getV2(),getV3(),getV4(),getV5(),getV6(),getV7(),getV8(),getV9(),getV10(),val);
    }
}
