/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/TupleN.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;

/**
 * 包含 1 个元素的元组。
 * <p>提供类型安全的元素访问和元组操作。</p>
 * @param <T1> 第2个元素类型
 */
@ReadOnly
public final class Tuple1<T1> extends Tuple {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 创建一个包含 1 个指定元素的元组。
     *
     * @param v1 第1个元素
     */
    public Tuple1(T1 v1) {
        super(v1);
    }

    /**
     * 返回第 1 个元素。
     *
     * @return 第 1 个元素
     */
    public T1 getV1() { return (T1)getVn(1); }
    /**
     * 返回唯一元素的值。
     *
     * @return 元素值
     */
    public T1 getValue() { return getV1(); }
    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple1<T1> clone() {
        return this;
    }

    /**
     * 返回替换第 1 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple1<T1> withV1(T1 val) {
        return new Tuple1<>(val);
    }
}
