/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/TupleN.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;

/**
 * 包含 5 个元素的元组。
 * <p>提供类型安全的元素访问和元组操作。</p>
 * @param <T1> 第2个元素类型
 * @param <T2> 第3个元素类型
 * @param <T3> 第4个元素类型
 * @param <T4> 第5个元素类型
 * @param <T5> 第6个元素类型
 */
@ReadOnly
public final class Tuple5<T1,T2,T3,T4,T5> extends Tuple {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 创建一个包含 5 个指定元素的元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     */
    public Tuple5(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5) {
        super(v1,v2,v3,v4,v5);
    }

    /**
     * 返回第 1 个元素。
     *
     * @return 第 1 个元素
     */
    public T1 getV1() { return (T1)getVn(1); }
    /**
     * 返回第 2 个元素。
     *
     * @return 第 2 个元素
     */
    public T2 getV2() { return (T2)getVn(2); }
    /**
     * 返回第 3 个元素。
     *
     * @return 第 3 个元素
     */
    public T3 getV3() { return (T3)getVn(3); }
    /**
     * 返回第 4 个元素。
     *
     * @return 第 4 个元素
     */
    public T4 getV4() { return (T4)getVn(4); }
    /**
     * 返回第 5 个元素。
     *
     * @return 第 5 个元素
     */
    public T5 getV5() { return (T5)getVn(5); }
    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple5<T1,T2,T3,T4,T5> clone() {
        return this;
    }

    /**
     * 返回替换第 1 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple5<T1,T2,T3,T4,T5> withV1(T1 val) {
        return new Tuple5<>(val,getV2(),getV3(),getV4(),getV5());
    }
    /**
     * 返回替换第 2 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple5<T1,T2,T3,T4,T5> withV2(T2 val) {
        return new Tuple5<>(getV1(),val,getV3(),getV4(),getV5());
    }
    /**
     * 返回替换第 3 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple5<T1,T2,T3,T4,T5> withV3(T3 val) {
        return new Tuple5<>(getV1(),getV2(),val,getV4(),getV5());
    }
    /**
     * 返回替换第 4 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple5<T1,T2,T3,T4,T5> withV4(T4 val) {
        return new Tuple5<>(getV1(),getV2(),getV3(),val,getV5());
    }
    /**
     * 返回替换第 5 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple5<T1,T2,T3,T4,T5> withV5(T5 val) {
        return new Tuple5<>(getV1(),getV2(),getV3(),getV4(),val);
    }
}
