/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/TupleN.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;

/**
 * 包含 3 个元素的元组。
 * <p>提供类型安全的元素访问和元组操作。</p>
 * @param <T1> 第2个元素类型
 * @param <T2> 第3个元素类型
 * @param <T3> 第4个元素类型
 */
@ReadOnly
public final class Tuple3<T1,T2,T3> extends Tuple {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 创建一个包含 3 个指定元素的元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     */
    public Tuple3(T1 v1,T2 v2,T3 v3) {
        super(v1,v2,v3);
    }

    /**
     * 返回第 1 个元素。
     *
     * @return 第 1 个元素
     */
    public T1 getV1() { return (T1)getVn(1); }
    /**
     * 返回第 2 个元素。
     *
     * @return 第 2 个元素
     */
    public T2 getV2() { return (T2)getVn(2); }
    /**
     * 返回第 3 个元素。
     *
     * @return 第 3 个元素
     */
    public T3 getV3() { return (T3)getVn(3); }
    /**
     * 返回第一个元素（左值）。
     *
     * @return 第一个元素
     */
    public T1 getLeft() { return getV1(); }
    /**
     * 返回第二个元素（中间值）。
     *
     * @return 第二个元素
     */
    public T2 getMid() { return getV2(); }
    /**
     * 返回第三个元素（右值）。
     *
     * @return 第三个元素
     */
    public T3 getRight() { return getV3(); }
    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple3<T1,T2,T3> clone() {
        return this;
    }

    /**
     * 返回替换第 1 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple3<T1,T2,T3> withV1(T1 val) {
        return new Tuple3<>(val,getV2(),getV3());
    }
    /**
     * 返回替换第 2 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple3<T1,T2,T3> withV2(T2 val) {
        return new Tuple3<>(getV1(),val,getV3());
    }
    /**
     * 返回替换第 3 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple3<T1,T2,T3> withV3(T3 val) {
        return new Tuple3<>(getV1(),getV2(),val);
    }
}
