/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/Tuple.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Objects;
import java.util.Spliterator;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * 元组类。
 * <p>提供类型安全的异构元素容器，支持 arity 查询和元素访问。</p>
 *
 * @since 1.0
 */
@ReadOnly
public class Tuple implements Cloneable, Comparable<Tuple>, Serializable, Iterable<Object> {
    @Serial
    private static final long serialVersionUID = 1L;
    private final Object[] contents;

    /**
     * 创建一个包含指定元素的元组。
     *
     * @param vs 元组元素数组
     */
    protected Tuple(Object... vs) {
        this.contents = Objects.requireNonNull(vs);
    }

    /**
     * 返回元组中元素的个数。
     *
     * @return 元素个数
     */
    public int size() {
        return contents.length;
    }

    /**
     * 返回指定位置的元素（从 1 开始计数）。
     *
     * @param i 元素索引（从 1 开始）
     * @return 指定位置的元素
     * @throws IndexOutOfBoundsException 如果索引越界
     */
    public Object getVn(int i) {
        return contents[Objects.checkIndex(i - 1, contents.length)];
    }

    @SuppressWarnings("unchecked")
    private static <T> int compare(T o1, T o2) {
        if (o1 == null && o2 == null) return 0;
        if (o1 == null) return -1;
        if (o2 == null) return 1;
        if (o1 instanceof Comparable) {
            return ((Comparable<T>) o1).compareTo(o2);
        }
        throw new ClassCastException("not comparable: " + o1.getClass());
    }

    /**
     * 按字典顺序比较两个元组。
     *
     * @param v 要比较的元组
     * @return 如果此元组小于、等于或大于指定元组，则返回负整数、零或正整数
     */
    @Override
    public int compareTo(Tuple v) {
        int n = Math.min(this.size(), v.size());
        for (int i = 1; i <= n; i++) {
            int result = compare(this.getVn(i), v.getVn(i));
            if (result != 0) return result;
        }
        return Integer.compare(this.size(), v.size());
    }

    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple clone() {
        return this;
    }

    /**
     * 创建包含 1 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param v1 第1个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1> Tuple1<T1> of(T1 v1) {
        return new Tuple1<>(v1);
    }
    /**
     * 创建包含 2 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2> Tuple2<T1,T2> of(T1 v1,T2 v2) {
        return new Tuple2<>(v1,v2);
    }
    /**
     * 创建包含 3 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3> Tuple3<T1,T2,T3> of(T1 v1,T2 v2,T3 v3) {
        return new Tuple3<>(v1,v2,v3);
    }
    /**
     * 创建包含 4 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4> Tuple4<T1,T2,T3,T4> of(T1 v1,T2 v2,T3 v3,T4 v4) {
        return new Tuple4<>(v1,v2,v3,v4);
    }
    /**
     * 创建包含 5 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5> Tuple5<T1,T2,T3,T4,T5> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5) {
        return new Tuple5<>(v1,v2,v3,v4,v5);
    }
    /**
     * 创建包含 6 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6> Tuple6<T1,T2,T3,T4,T5,T6> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6) {
        return new Tuple6<>(v1,v2,v3,v4,v5,v6);
    }
    /**
     * 创建包含 7 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7> Tuple7<T1,T2,T3,T4,T5,T6,T7> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7) {
        return new Tuple7<>(v1,v2,v3,v4,v5,v6,v7);
    }
    /**
     * 创建包含 8 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8> Tuple8<T1,T2,T3,T4,T5,T6,T7,T8> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8) {
        return new Tuple8<>(v1,v2,v3,v4,v5,v6,v7,v8);
    }
    /**
     * 创建包含 9 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9> Tuple9<T1,T2,T3,T4,T5,T6,T7,T8,T9> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9) {
        return new Tuple9<>(v1,v2,v3,v4,v5,v6,v7,v8,v9);
    }
    /**
     * 创建包含 10 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> Tuple10<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10) {
        return new Tuple10<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10);
    }
    /**
     * 创建包含 11 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> Tuple11<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11) {
        return new Tuple11<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11);
    }
    /**
     * 创建包含 12 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12> Tuple12<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12) {
        return new Tuple12<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12);
    }
    /**
     * 创建包含 13 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13> Tuple13<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13) {
        return new Tuple13<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13);
    }
    /**
     * 创建包含 14 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14> Tuple14<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14) {
        return new Tuple14<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14);
    }
    /**
     * 创建包含 15 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15> Tuple15<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15) {
        return new Tuple15<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15);
    }
    /**
     * 创建包含 16 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param <T16> 第16个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @param v16 第16个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16> Tuple16<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15,T16 v16) {
        return new Tuple16<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16);
    }
    /**
     * 创建包含 17 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param <T16> 第16个元素类型
     * @param <T17> 第17个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @param v16 第16个元素
     * @param v17 第17个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17> Tuple17<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15,T16 v16,T17 v17) {
        return new Tuple17<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17);
    }
    /**
     * 创建包含 18 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param <T16> 第16个元素类型
     * @param <T17> 第17个元素类型
     * @param <T18> 第18个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @param v16 第16个元素
     * @param v17 第17个元素
     * @param v18 第18个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18> Tuple18<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15,T16 v16,T17 v17,T18 v18) {
        return new Tuple18<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18);
    }
    /**
     * 创建包含 19 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param <T16> 第16个元素类型
     * @param <T17> 第17个元素类型
     * @param <T18> 第18个元素类型
     * @param <T19> 第19个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @param v16 第16个元素
     * @param v17 第17个元素
     * @param v18 第18个元素
     * @param v19 第19个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19> Tuple19<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15,T16 v16,T17 v17,T18 v18,T19 v19) {
        return new Tuple19<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19);
    }
    /**
     * 创建包含 20 个元素的类型化元组。
     *
     * @param <T1> 第1个元素类型
     * @param <T2> 第2个元素类型
     * @param <T3> 第3个元素类型
     * @param <T4> 第4个元素类型
     * @param <T5> 第5个元素类型
     * @param <T6> 第6个元素类型
     * @param <T7> 第7个元素类型
     * @param <T8> 第8个元素类型
     * @param <T9> 第9个元素类型
     * @param <T10> 第10个元素类型
     * @param <T11> 第11个元素类型
     * @param <T12> 第12个元素类型
     * @param <T13> 第13个元素类型
     * @param <T14> 第14个元素类型
     * @param <T15> 第15个元素类型
     * @param <T16> 第16个元素类型
     * @param <T17> 第17个元素类型
     * @param <T18> 第18个元素类型
     * @param <T19> 第19个元素类型
     * @param <T20> 第20个元素类型
     * @param v1 第1个元素
     * @param v2 第2个元素
     * @param v3 第3个元素
     * @param v4 第4个元素
     * @param v5 第5个元素
     * @param v6 第6个元素
     * @param v7 第7个元素
     * @param v8 第8个元素
     * @param v9 第9个元素
     * @param v10 第10个元素
     * @param v11 第11个元素
     * @param v12 第12个元素
     * @param v13 第13个元素
     * @param v14 第14个元素
     * @param v15 第15个元素
     * @param v16 第16个元素
     * @param v17 第17个元素
     * @param v18 第18个元素
     * @param v19 第19个元素
     * @param v20 第20个元素
     * @return 包含指定元素的新类型化元组
     */
    public static <T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20> Tuple20<T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20> of(T1 v1,T2 v2,T3 v3,T4 v4,T5 v5,T6 v6,T7 v7,T8 v8,T9 v9,T10 v10,T11 v11,T12 v12,T13 v13,T14 v14,T15 v15,T16 v16,T17 v17,T18 v18,T19 v19,T20 v20) {
        return new Tuple20<>(v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20);
    }
    /**
     * 将元组内容转换为数组。
     *
     * @return 包含所有元素的新数组
     */
    public Object[] toArray() {
        return contents.clone();
    }

    /**
     * 将元组内容转换为列表。
     *
     * @return 包含所有元素的列表
     */
    public List<Object> toList() {
        return Arrays.asList(contents.clone());
    }

    /**
     * 返回元组元素的迭代器。
     *
     * @return 迭代器
     */
    @Override
    public Iterator<Object> iterator() {
        return toList().iterator();
    }

    /**
     * 返回元组分隔迭代器。
     *
     * @return 分隔迭代器
     */
    @Override
    public Spliterator<Object> spliterator() {
        return Arrays.spliterator(contents);
    }

    /**
     * 返回元组元素的顺序流。
     *
     * @return 顺序流
     */
    public Stream<Object> stream() {
        return StreamSupport.stream(spliterator(), false);
    }

    /**
     * 比较此元组与指定对象是否相等。
     *
     * @param o 要比较的对象
     * @return 如果元素数组相等则返回 true
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tuple)) return false;
        return Arrays.equals(contents, ((Tuple) o).contents);
    }

    /**
     * 返回此元组的哈希码。
     *
     * @return 哈希码值
     */
    @Override
    public int hashCode() {
        return Arrays.hashCode(contents);
    }

    /**
     * 返回此元组的字符串表示。
     * <p>格式为 {@code <elem1,elem2,...>}。</p>
     *
     * @return 字符串表示
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("<");
        for (Object obj : contents) {
            sb.append(obj).append(',');
        }
        if (contents.length > 0) sb.deleteCharAt(sb.length() - 1);
        sb.append('>');
        return sb.toString();
    }
}
