/*
 * WARNING: Do NOT edit manually. auto generated by flora-ramet.
 * edit "tuple/TupleN.ramet" and regenerate instead.
 */

package com.flora.container.tuple;

import com.flora.tag.ReadOnly;
import java.io.Serial;

/**
 * 包含 2 个元素的元组。
 * <p>提供类型安全的元素访问和元组操作。</p>
 * @param <T1> 第2个元素类型
 * @param <T2> 第3个元素类型
 */
@ReadOnly
public final class Tuple2<T1,T2> extends Tuple {
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * 创建一个包含 2 个指定元素的元组。
     *
     * @param v1 第1个元素
     * @param v2 第2个元素
     */
    public Tuple2(T1 v1,T2 v2) {
        super(v1,v2);
    }

    /**
     * 返回第 1 个元素。
     *
     * @return 第 1 个元素
     */
    public T1 getV1() { return (T1)getVn(1); }
    /**
     * 返回第 2 个元素。
     *
     * @return 第 2 个元素
     */
    public T2 getV2() { return (T2)getVn(2); }
    /**
     * 返回第一个元素（左值）。
     *
     * @return 第一个元素
     */
    public T1 getLeft() { return getV1(); }
    /**
     * 返回第二个元素（右值）。
     *
     * @return 第二个元素
     */
    public T2 getRight() { return getV2(); }
    /**
     * 返回此元组的浅拷贝。
     *
     * @return 浅拷贝的元组实例
     */
    @Override
    public Tuple2<T1,T2> clone() {
        return this;
    }

    /**
     * 返回替换第 1 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple2<T1,T2> withV1(T1 val) {
        return new Tuple2<>(val,getV2());
    }
    /**
     * 返回替换第 2 个元素后的新元组。
     *
     * @param val 新的元素值
     * @return 替换后的新元组
     */
    public Tuple2<T1,T2> withV2(T2 val) {
        return new Tuple2<>(getV1(),val);
    }
}
